apiVersion: v2
name: notesnook
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: common
  version: 24.1.5
  repository: oci://tccr.io/truecharts
  condition: ""
  alias: ""
  tags: []
  import-values: []
- name: mongodb
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.3.0
  condition: mongodb.enabled
  alias: mongo
